-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cities"
(
    city_name text NOT NULL,
    country text NOT NULL,
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    city_id bigserial NOT NULL,
    PRIMARY KEY (city_name, country),
    UNIQUE (city_id),
    UNIQUE (city_name, country)
);

CREATE TABLE IF NOT EXISTS public."Weather"
(
    date timestamp without time zone NOT NULL,
    temperature numeric,
    date_txt text,
    city_id bigint NOT NULL,
    PRIMARY KEY (city_id, date)
);

ALTER TABLE IF EXISTS public."Weather"
    ADD FOREIGN KEY (city_id)
    REFERENCES public."Cities" (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;